#!/bin/sh
# shellcheck shell=dash disable=SC3010
#
# simple RaspberryPi EEPROM/Bootloader check tool
#
# Copyright (c) 2024-2026 Jens Maus <mail@jens-maus.de>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Usage:
# rpi-eeprom-info
#

DT_BOOTLOADER_TS=${DT_BOOTLOADER_TS:-/proc/device-tree/chosen/bootloader/build-timestamp}
BOOTLOADER_UPDATE_IMAGE=${BOOTLOADER_UPDATE_IMAGE:-/boot/pieeprom.upd}

EXIT_SUCCESS=0
EXIT_UPDATE_REQUIRED=1
EXIT_FAILED=2

if [ -f "/sys/firmware/devicetree/base/system/linux,revision" ]; then
  BOARD_INFO="$(od -v -An -t x1 /sys/firmware/devicetree/base/system/linux,revision | tr -d ' \n')"
elif grep -q Revision /proc/cpuinfo; then
  BOARD_INFO="$(sed -n '/^Revision/s/^.*: \(.*\)/\1/p' < /proc/cpuinfo)"
elif command -v vcgencmd > /dev/null; then
  BOARD_INFO="$(vcgencmd otp_dump | grep '30:' | sed 's/.*://')"
else
  echo "No Raspberry Pi board info found"
  exit ${EXIT_FAILED}
fi

BOARD_TYPE=$(((0x$BOARD_INFO >> 4) & 0xff))
BOARD_REVISION=$((0x$BOARD_INFO & 0xf))
if [ $(((0x$BOARD_INFO >> 12) & 15)) = 3 ]; then
  BCM_CHIP=2711
elif [ $(((0x$BOARD_INFO >> 12) & 15)) = 4 ]; then
  BCM_CHIP=2712
else
  echo "Device does not have a Raspberry Pi bootloader EEPROM (only Pi 4 and Pi 5 do)."
  exit ${EXIT_FAILED}
fi

if [ ${BOARD_TYPE} -eq 17 ] && [ ${BOARD_REVISION} -lt 4 ]; then
  HAVE_VL805_EEPROM=1
else
  HAVE_VL805_EEPROM=0
fi

if [[ ! -f "${DT_BOOTLOADER_TS}" ]]; then
  echo "Bootloader build-timestamp not available at ${DT_BOOTLOADER_TS}" >&2
  exit ${EXIT_FAILED}
fi

if [ ! -f "${BOOTLOADER_UPDATE_IMAGE}" ]; then
  echo "Bootloader update image not available at ${BOOTLOADER_UPDATE_IMAGE}" >&2
  exit ${EXIT_FAILED}
fi

# Prefer device-tree to vcgencmd
BOOTLOADER_CURRENT_VERSION=$(printf "%d" "0x$(od "${DT_BOOTLOADER_TS}" -v -An -t x1 | tr -d ' ' )")
BOOTLOADER_UPDATE_VERSION=$(strings "${BOOTLOADER_UPDATE_IMAGE}" | grep BUILD_TIMESTAMP | sed 's/.*=//g')

if [[ "${BOOTLOADER_CURRENT_VERSION}" != "${BOOTLOADER_UPDATE_VERSION}" ]]; then
  echo "BOOTLOADER: update available"
  res=${EXIT_UPDATE_REQUIRED}
else
  echo "BOOTLOADER: up to date"
  res=${EXIT_SUCCESS}
fi

echo "   CURRENT: $(date -u "-d@${BOOTLOADER_CURRENT_VERSION}") (${BOOTLOADER_CURRENT_VERSION})"
echo "    LATEST: $(date -u "-d@${BOOTLOADER_UPDATE_VERSION}") (${BOOTLOADER_UPDATE_VERSION})"

if [ "${BCM_CHIP}" = 2711 ]; then
  echo ""
  if [ "${HAVE_VL805_EEPROM}" = 1 ]; then
    echo "  VL805_FW: Dedicated VL805 EEPROM (/boot/vl805.bin)"
  else
    echo "  VL805_FW: Using bootloader EEPROM"
  fi

  # get current running VL805 firmware version
  VL805_CURRENT_VERSION=$(for d in /sys/bus/pci/devices/*/; do
    [ "$(cat "${d}vendor" 2>/dev/null)" = "0x1106" ] && \
    [ "$(cat "${d}device" 2>/dev/null)" = "0x3483" ] && \
    od -A n -t x1 -j 80 -N 4 "${d}config" | awk '{print $4$3$2$1}' && break
  done)
  echo "   CURRENT: ${VL805_CURRENT_VERSION}"

  if [ "${HAVE_VL805_EEPROM}" = 1 ]; then
    VL805_UPDATE_VERSION=$(cat /boot/vl805.ver 2>/dev/null || echo "unknown")
    echo "    LATEST: ${VL805_UPDATE_VERSION}"
  fi
fi

exit ${res}
